-- AUTO-GENERATED by scripts/generate-seed-sql.mjs
-- Source of truth: src/app/data/sites.ts
-- 137 sites | Generated: 2026-09-26T13:07:07.781Z
-- Paste this into your Supabase SQL Editor to sync all 136 domains

INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('google', 'Google', 'https://google.com', 1, 'search', '85.0B / mo', 85000000000, 32787, '#4285F4', 'rgba(136, 136, 136, 0.15)', 100)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('youtube', 'YouTube', 'https://youtube.com', 2, 'entertainment', '34.8B / mo', 34800000000, 13242, '#ef4444', 'rgba(136, 136, 136, 0.15)', 40.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('facebook', 'Facebook', 'https://facebook.com', 3, 'social', '15.2B / mo', 15200000000, 5783, '#1877F2', 'rgba(136, 136, 136, 0.15)', 17.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('instagram', 'Instagram', 'https://instagram.com', 4, 'social', '6.8B / mo', 6800000000, 2587, '#E1306C', 'rgba(136, 136, 136, 0.15)', 8)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('chatgpt', 'ChatGPT', 'https://chatgpt.com', 5, 'ai', '5.5B / mo', 5500000000, 2092, '#10a37f', 'rgba(136, 136, 136, 0.15)', 6.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('wikipedia', 'Wikipedia', 'https://wikipedia.com', 6, 'reference', '4.5B / mo', 4500000000, 1712, '#72777D', 'rgba(136, 136, 136, 0.15)', 5.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('amazon', 'Amazon', 'https://amazon.com', 7, 'ecommerce', '4.2B / mo', 4200000000, 1598, '#ff9900', 'rgba(136, 136, 136, 0.15)', 4.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('x', 'X (Twitter)', 'https://x.com', 8, 'social', '4.2B / mo', 4200000000, 1598, '#ffffff', 'rgba(136, 136, 136, 0.15)', 4.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('whatsapp', 'WhatsApp', 'https://whatsapp.com', 9, 'social', '2.9B / mo', 2900000000, 1103, '#25d366', 'rgba(136, 136, 136, 0.15)', 3.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('reddit', 'Reddit', 'https://reddit.com', 10, 'social', '2.8B / mo', 2800000000, 1065, '#FF4500', 'rgba(136, 136, 136, 0.15)', 3.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('tiktok', 'TikTok', 'https://tiktok.com', 11, 'social', '2.8B / mo', 2800000000, 1065, '#01f1e2', 'rgba(136, 136, 136, 0.15)', 3.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('yahoo', 'Yahoo', 'https://yahoo.com', 12, 'search', '2.8B / mo', 2800000000, 1065, '#6001d2', 'rgba(136, 136, 136, 0.15)', 3.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('yandex', 'Yandex', 'https://yandex.com', 13, 'search', '2.5B / mo', 2500000000, 951, '#ffcc00', 'rgba(136, 136, 136, 0.15)', 2.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('baidu', 'Baidu', 'https://baidu.com', 14, 'search', '2.2B / mo', 2200000000, 837, '#2319dc', 'rgba(136, 136, 136, 0.15)', 2.6)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('netflix', 'Netflix', 'https://netflix.com', 15, 'entertainment', '2.1B / mo', 2100000000, 799, '#e50914', 'rgba(136, 136, 136, 0.15)', 2.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('openai', 'OpenAI', 'https://openai.com', 16, 'dev', '2.0B / mo', 2000000000, 772, '#10a37f', 'rgba(136, 136, 136, 0.15)', 2.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bing', 'Bing', 'https://bing.com', 17, 'search', '1.8B / mo', 1800000000, 684, '#008373', 'rgba(136, 136, 136, 0.15)', 2.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('microsoft', 'Microsoft', 'https://microsoft.com', 18, 'dev', '1.8B / mo', 1800000000, 684, '#0078d4', 'rgba(136, 136, 136, 0.15)', 2.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('linkedin', 'LinkedIn', 'https://linkedin.com', 19, 'social', '1.8B / mo', 1750000000, 665, '#0a66c2', 'rgba(136, 136, 136, 0.15)', 2.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('office', 'Office 365', 'https://office.com', 20, 'dev', '1.6B / mo', 1600000000, 608, '#eb3c00', 'rgba(136, 136, 136, 0.15)', 1.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('twitch', 'Twitch', 'https://twitch.com', 21, 'entertainment', '1.1B / mo', 1150000000, 437, '#9146ff', 'rgba(136, 136, 136, 0.15)', 1.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('pinterest', 'Pinterest', 'https://pinterest.com', 22, 'social', '1.1B / mo', 1100000000, 418, '#bd081c', 'rgba(136, 136, 136, 0.15)', 1.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('weather', 'Weather', 'https://weather.com', 23, 'reference', '1.1B / mo', 1100000000, 418, '#002f6c', 'rgba(136, 136, 136, 0.15)', 1.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('github', 'GitHub', 'https://github.com', 24, 'dev', '1.0B / mo', 1000000000, 380, '#24292f', 'rgba(136, 136, 136, 0.15)', 1.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('zoom', 'Zoom', 'https://zoom.com', 25, 'dev', '920.0M / mo', 920000000, 350, '#2d8cff', 'rgba(136, 136, 136, 0.15)', 1.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('ebay', 'eBay', 'https://ebay.com', 26, 'ecommerce', '900.0M / mo', 900000000, 342, '#e53238', 'rgba(136, 136, 136, 0.15)', 1.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('gemini', 'Gemini', 'https://gemini.com', 27, 'ai', '860.0M / mo', 860000000, 327, '#4a90e2', 'rgba(136, 136, 136, 0.15)', 1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('duckduckgo', 'DuckDuckGo', 'https://duckduckgo.com', 28, 'search', '850.0M / mo', 850000000, 323, '#de5833', 'rgba(136, 136, 136, 0.15)', 1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('quora', 'Quora', 'https://quora.com', 29, 'reference', '750.0M / mo', 750000000, 285, '#b92b27', 'rgba(136, 136, 136, 0.15)', 0.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('telegram', 'Telegram', 'https://telegram.com', 30, 'social', '750.0M / mo', 750000000, 285, '#229ed9', 'rgba(136, 136, 136, 0.15)', 0.9)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('aliexpress', 'AliExpress', 'https://aliexpress.com', 31, 'ecommerce', '680.0M / mo', 680000000, 258, '#ff4747', 'rgba(136, 136, 136, 0.15)', 0.8)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('canva', 'Canva', 'https://canva.com', 32, 'dev', '650.0M / mo', 650000000, 247, '#00c4cc', 'rgba(136, 136, 136, 0.15)', 0.8)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('nytimes', 'NY Times', 'https://nytimes.com', 33, 'news', '650.0M / mo', 650000000, 247, '#555555', 'rgba(136, 136, 136, 0.15)', 0.8)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bbc', 'BBC', 'https://bbc.com', 34, 'news', '580.0M / mo', 580000000, 220, '#ae251f', 'rgba(136, 136, 136, 0.15)', 0.7)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('discord', 'Discord', 'https://discord.com', 35, 'social', '580.0M / mo', 580000000, 220, '#5865f2', 'rgba(136, 136, 136, 0.15)', 0.7)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('spotify', 'Spotify', 'https://spotify.com', 36, 'entertainment', '560.0M / mo', 560000000, 213, '#1db954', 'rgba(136, 136, 136, 0.15)', 0.7)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('roblox', 'Roblox', 'https://roblox.com', 37, 'entertainment', '545.0M / mo', 545000000, 207, '#888888', 'rgba(136, 136, 136, 0.15)', 0.6)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('apple', 'Apple', 'https://apple.com', 38, 'dev', '520.0M / mo', 520000000, 197, '#a3aaae', 'rgba(136, 136, 136, 0.15)', 0.6)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('booking', 'Booking.com', 'https://booking.com', 39, 'ecommerce', '520.0M / mo', 520000000, 197, '#003580', 'rgba(136, 136, 136, 0.15)', 0.6)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('cnn', 'CNN', 'https://cnn.com', 40, 'news', '520.0M / mo', 520000000, 197, '#cc0000', 'rgba(136, 136, 136, 0.15)', 0.6)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('walmart', 'Walmart', 'https://walmart.com', 41, 'ecommerce', '510.0M / mo', 510000000, 194, '#0071dc', 'rgba(136, 136, 136, 0.15)', 0.6)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('imgur', 'Imgur', 'https://imgur.com', 42, 'entertainment', '450.0M / mo', 450000000, 171, '#1bb76e', 'rgba(136, 136, 136, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('paypal', 'PayPal', 'https://paypal.com', 43, 'finance', '440.0M / mo', 440000000, 167, '#003087', 'rgba(136, 136, 136, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('etsy', 'Etsy', 'https://etsy.com', 44, 'ecommerce', '420.0M / mo', 420000000, 159, '#d5641c', 'rgba(136, 136, 136, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('naver', 'Naver', 'https://naver.com', 45, 'search', '400.0M / mo', 400000000, 152, '#03c75a', 'rgba(136, 136, 136, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bilibili', 'Bilibili', 'https://bilibili.com', 46, 'entertainment', '390.0M / mo', 390000000, 148, '#00a1d6', 'rgba(136, 136, 136, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('stackoverflow', 'Stack Overflow', 'https://stackoverflow.com', 47, 'dev', '390.0M / mo', 390000000, 148, '#f48024', 'rgba(136, 136, 136, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('imdb', 'IMDb', 'https://imdb.com', 48, 'reference', '370.0M / mo', 370000000, 140, '#e6b91e', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('fandom', 'Fandom', 'https://fandom.com', 49, 'reference', '360.0M / mo', 360000000, 136, '#00d6d6', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('disneyplus', 'Disney+', 'https://disneyplus.com', 50, 'entertainment', '350.0M / mo', 350000000, 133, '#001d3d', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('target', 'Target', 'https://target.com', 51, 'ecommerce', '340.0M / mo', 340000000, 129, '#cc0000', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('theguardian', 'The Guardian', 'https://theguardian.com', 52, 'news', '340.0M / mo', 340000000, 129, '#005689', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('mailru', 'Mail.ru', 'https://mailru.com', 53, 'news', '330.0M / mo', 330000000, 125, '#005eff', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('adobe', 'Adobe', 'https://adobe.com', 54, 'dev', '310.0M / mo', 310000000, 117, '#ff0000', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('steam', 'Steam', 'https://steam.com', 55, 'entertainment', '305.0M / mo', 305000000, 116, '#171a21', 'rgba(136, 136, 136, 0.15)', 0.4)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('globo', 'Globo', 'https://globo.com', 56, 'news', '295.0M / mo', 295000000, 112, '#ff4a4a', 'rgba(136, 136, 136, 0.15)', 0.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('tradingview', 'TradingView', 'https://tradingview.com', 57, 'finance', '220.0M / mo', 220000000, 83, '#131722', 'rgba(136, 136, 136, 0.15)', 0.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('espn', 'ESPN', 'https://espn.com', 58, 'entertainment', '210.0M / mo', 210000000, 79, '#ff002b', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('huggingface', 'Hugging Face', 'https://huggingface.com', 59, 'ai', '210.0M / mo', 210000000, 79, '#ffc72c', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('salesforce', 'Salesforce', 'https://salesforce.com', 60, 'dev', '198.0M / mo', 198000000, 75, '#00a1e0', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('dailymail', 'Daily Mail', 'https://dailymail.com', 61, 'news', '195.0M / mo', 195000000, 74, '#00356b', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('medium', 'Medium', 'https://medium.com', 62, 'reference', '180.0M / mo', 180000000, 68, '#333333', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('vimeo', 'Vimeo', 'https://vimeo.com', 63, 'entertainment', '178.0M / mo', 178000000, 67, '#1ab7ea', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('dropbox', 'Dropbox', 'https://dropbox.com', 64, 'dev', '172.0M / mo', 172000000, 65, '#0061fe', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('slack', 'Slack', 'https://slack.com', 65, 'dev', '168.0M / mo', 168000000, 63, '#4a154b', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('investing', 'Investing.com', 'https://investing.com', 66, 'finance', '162.0M / mo', 162000000, 61, '#1b4f72', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('binance', 'Binance', 'https://binance.com', 67, 'finance', '160.0M / mo', 160000000, 60, '#f3ba2f', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('airbnb', 'Airbnb', 'https://airbnb.com', 68, 'ecommerce', '155.0M / mo', 155000000, 58, '#ff5a5f', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('figma', 'Figma', 'https://figma.com', 69, 'dev', '152.0M / mo', 152000000, 57, '#f24e1e', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bloomberg', 'Bloomberg', 'https://bloomberg.com', 70, 'finance', '148.0M / mo', 148000000, 56, '#3b5998', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('uber', 'Uber', 'https://uber.com', 71, 'ecommerce', '148.0M / mo', 148000000, 56, '#000000', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('coinbase', 'Coinbase', 'https://coinbase.com', 72, 'finance', '145.0M / mo', 145000000, 55, '#0052ff', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('midjourney', 'Midjourney', 'https://midjourney.com', 73, 'ai', '145.0M / mo', 145000000, 55, '#1a1a2e', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('claude', 'Claude.ai', 'https://claude.com', 74, 'ai', '135.0M / mo', 135000000, 51, '#d97706', 'rgba(136, 136, 136, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('wikihow', 'wikiHow', 'https://wikihow.com', 75, 'reference', '122.0M / mo', 122000000, 46, '#93b546', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('shopify', 'Shopify', 'https://shopify.com', 76, 'ecommerce', '120.0M / mo', 120000000, 45, '#96bf48', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('indeed', 'Indeed', 'https://indeed.com', 77, 'ecommerce', '118.0M / mo', 118000000, 44, '#2164f3', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('merriamwebster', 'Merriam-Webster', 'https://merriamwebster.com', 78, 'reference', '118.0M / mo', 118000000, 44, '#0f4a7c', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('accuweather', 'AccuWeather', 'https://accuweather.com', 79, 'reference', '115.0M / mo', 115000000, 43, '#f05023', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('ikea', 'IKEA', 'https://ikea.com', 80, 'ecommerce', '112.0M / mo', 112000000, 42, '#ffcc00', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('speedtest', 'Speedtest', 'https://speedtest.com', 81, 'dev', '112.0M / mo', 112000000, 42, '#141b2b', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bestbuy', 'Best Buy', 'https://bestbuy.com', 82, 'ecommerce', '108.0M / mo', 108000000, 41, '#0046be', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('patreon', 'Patreon', 'https://patreon.com', 83, 'social', '108.0M / mo', 108000000, 41, '#ff424d', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('nike', 'Nike', 'https://nike.com', 84, 'ecommerce', '104.0M / mo', 104000000, 39, '#111111', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('hulu', 'Hulu', 'https://hulu.com', 85, 'entertainment', '102.0M / mo', 102000000, 38, '#1ce783', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('craigslist', 'Craigslist', 'https://craigslist.com', 86, 'ecommerce', '98.0M / mo', 98000000, 37, '#551a8b', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('soundcloud', 'SoundCloud', 'https://soundcloud.com', 87, 'entertainment', '96.0M / mo', 96000000, 36, '#ff5500', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('max', 'Max', 'https://max.com', 88, 'entertainment', '94.0M / mo', 94000000, 35, '#002be7', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('ign', 'IGN', 'https://ign.com', 89, 'entertainment', '90.0M / mo', 90000000, 34, '#bf1313', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('deviantart', 'DeviantArt', 'https://deviantart.com', 90, 'entertainment', '88.0M / mo', 88000000, 33, '#05cc47', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('reuters', 'Reuters', 'https://reuters.com', 91, 'news', '84.0M / mo', 84000000, 31, '#ff8000', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('forbes', 'Forbes', 'https://forbes.com', 92, 'news', '82.0M / mo', 82000000, 31, '#00507d', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('npm', 'NPM', 'https://npm.com', 93, 'dev', '80.0M / mo', 80000000, 30, '#cb3837', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('vercel', 'Vercel', 'https://vercel.com', 94, 'dev', '80.0M / mo', 80000000, 30, '#000000', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('wired', 'Wired', 'https://wired.com', 95, 'news', '78.0M / mo', 78000000, 29, '#000000', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('techcrunch', 'TechCrunch', 'https://techcrunch.com', 96, 'news', '75.0M / mo', 75000000, 28, '#028000', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('gitlab', 'GitLab', 'https://gitlab.com', 97, 'dev', '72.0M / mo', 72000000, 27, '#fc6d26', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('robinhood', 'Robinhood', 'https://robinhood.com', 98, 'finance', '72.0M / mo', 72000000, 27, '#00c805', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('docker', 'Docker', 'https://docker.com', 99, 'dev', '70.0M / mo', 70000000, 26, '#0db7ed', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('netlify', 'Netlify', 'https://netlify.com', 100, 'dev', '68.0M / mo', 68000000, 25, '#00ad9f', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('stackexchange', 'Stack Exchange', 'https://stackexchange.com', 101, 'reference', '62.0M / mo', 62000000, 23, '#0072bc', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('stripe', 'Stripe', 'https://stripe.com', 102, 'finance', '62.0M / mo', 62000000, 23, '#635bff', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('wunderground', 'Weather Underground', 'https://wunderground.com', 103, 'reference', '58.0M / mo', 58000000, 22, '#1a2b4c', 'rgba(136, 136, 136, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('threads', 'Threads', 'https://threads.net', 104, 'social', '380.0M / mo', 380000000, 144, '#ffffff', 'rgba(255, 255, 255, 0.15)', 0.5)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('kick', 'Kick', 'https://kick.com', 105, 'entertainment', '165.0M / mo', 165000000, 62, '#53fc18', 'rgba(83, 252, 24, 0.2)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('perplexity', 'Perplexity', 'https://perplexity.ai', 106, 'ai', '135.0M / mo', 135000000, 51, '#22b8cd', 'rgba(34, 184, 205, 0.2)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('substack', 'Substack', 'https://substack.com', 107, 'reference', '110.0M / mo', 110000000, 41, '#ff6719', 'rgba(255, 103, 25, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bsky', 'Bluesky', 'https://bsky.app', 108, 'social', '85.0M / mo', 85000000, 32, '#0285ff', 'rgba(2, 133, 255, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('suno', 'Suno', 'https://suno.com', 109, 'ai', '55.0M / mo', 55000000, 20, '#ff3366', 'rgba(255, 51, 102, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('cursor', 'Cursor', 'https://cursor.com', 110, 'dev', '48.0M / mo', 48000000, 18, '#00f0ff', 'rgba(0, 240, 255, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('supabase', 'Supabase', 'https://supabase.com', 111, 'dev', '42.0M / mo', 42000000, 16, '#3ecf8e', 'rgba(62, 207, 142, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('deepseek', 'DeepSeek', 'https://deepseek.com', 112, 'ai', '185.0M / mo', 185000000, 70, '#1e88e5', 'rgba(30, 136, 229, 0.2)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('temu', 'Temu', 'https://temu.com', 113, 'ecommerce', '620.0M / mo', 620000000, 236, '#ff6600', 'rgba(255, 102, 0, 0.2)', 0.7)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('characterai', 'Character.ai', 'https://character.ai', 114, 'ai', '220.0M / mo', 220000000, 84, '#6366f1', 'rgba(99, 102, 241, 0.2)', 0.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('notion', 'Notion', 'https://notion.so', 115, 'dev', '180.0M / mo', 180000000, 68, '#ffffff', 'rgba(255, 255, 255, 0.15)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('cloudflare', 'Cloudflare', 'https://cloudflare.com', 116, 'dev', '165.0M / mo', 165000000, 63, '#f38020', 'rgba(243, 128, 32, 0.2)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('shein', 'Shein', 'https://shein.com', 117, 'ecommerce', '290.0M / mo', 290000000, 110, '#ffffff', 'rgba(255, 255, 255, 0.15)', 0.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('elevenlabs', 'ElevenLabs', 'https://elevenlabs.io', 118, 'ai', '42.0M / mo', 42000000, 16, '#ffffff', 'rgba(255, 255, 255, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('poe', 'Poe', 'https://poe.com', 119, 'ai', '65.0M / mo', 65000000, 25, '#6d28d9', 'rgba(109, 40, 217, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('linear', 'Linear', 'https://linear.app', 120, 'dev', '28.0M / mo', 28000000, 11, '#5e6ad2', 'rgba(94, 106, 210, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('replit', 'Replit', 'https://replit.com', 121, 'dev', '45.0M / mo', 45000000, 17, '#f26207', 'rgba(242, 98, 7, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('mistral', 'Mistral AI', 'https://mistral.ai', 122, 'ai', '35.0M / mo', 35000000, 13, '#fd531e', 'rgba(253, 83, 30, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('chess', 'Chess.com', 'https://chess.com', 123, 'entertainment', '250.0M / mo', 250000000, 95, '#81b64c', 'rgba(129, 182, 76, 0.2)', 0.3)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('crunchyroll', 'Crunchyroll', 'https://crunchyroll.com', 124, 'entertainment', '140.0M / mo', 140000000, 53, '#f47521', 'rgba(244, 117, 33, 0.2)', 0.2)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('epicgames', 'Epic Games', 'https://epicgames.com', 125, 'entertainment', '110.0M / mo', 110000000, 42, '#ffffff', 'rgba(255, 255, 255, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('civitai', 'Civitai', 'https://civitai.com', 126, 'ai', '52.0M / mo', 52000000, 20, '#2563eb', 'rgba(37, 99, 235, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('postman', 'Postman', 'https://postman.com', 127, 'dev', '38.0M / mo', 38000000, 14, '#ff6c37', 'rgba(255, 108, 55, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('runwayml', 'Runway', 'https://runwayml.com', 128, 'ai', '30.0M / mo', 30000000, 11, '#00ff87', 'rgba(0, 255, 135, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('revolut', 'Revolut', 'https://revolut.com', 129, 'finance', '40.0M / mo', 40000000, 15, '#0075eb', 'rgba(0, 117, 235, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('coinmarketcap', 'CoinMarketCap', 'https://coinmarketcap.com', 130, 'finance', '120.0M / mo', 120000000, 46, '#3861fb', 'rgba(56, 97, 251, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('wise', 'Wise', 'https://wise.com', 131, 'finance', '55.0M / mo', 55000000, 21, '#9fe870', 'rgba(159, 232, 112, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('bybit', 'Bybit', 'https://bybit.com', 132, 'finance', '60.0M / mo', 60000000, 23, '#f7a600', 'rgba(247, 166, 0, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('letterboxd', 'Letterboxd', 'https://letterboxd.com', 133, 'entertainment', '45.0M / mo', 45000000, 17, '#00e054', 'rgba(0, 224, 84, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('digitalocean', 'DigitalOcean', 'https://digitalocean.com', 134, 'dev', '32.0M / mo', 32000000, 12, '#0080ff', 'rgba(0, 128, 255, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('sentry', 'Sentry', 'https://sentry.io', 135, 'dev', '25.0M / mo', 25000000, 10, '#362d59', 'rgba(255, 255, 255, 0.15)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('luma', 'Luma AI', 'https://lumalabs.ai', 136, 'ai', '22.0M / mo', 22000000, 8, '#ff3b30', 'rgba(255, 59, 48, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;
INSERT INTO public.sites (id, name, url, rank, category, baseline, baseline_raw, rate, color, glow, progress) VALUES ('jira', 'Jira', 'https://atlassian.com', 137, 'dev', '68.0M / mo', 68000000, 26, '#0052cc', 'rgba(0, 82, 204, 0.2)', 0.1)
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, url = EXCLUDED.url, rank = EXCLUDED.rank,
    category = EXCLUDED.category, baseline = EXCLUDED.baseline,
    baseline_raw = EXCLUDED.baseline_raw, rate = EXCLUDED.rate,
    color = EXCLUDED.color, glow = EXCLUDED.glow,
    progress = EXCLUDED.progress;