// AUTO-GENERATED by scripts/generate-countries.ts
// Run `npx tsx scripts/generate-countries.ts` to populate this file.
// This placeholder ensures the build succeeds before generation is run.

import { CountryData } from './countries';

export const GENERATED_COUNTRIES: CountryData[] = [];
